### PR TITLE
Readme: Add how to get started

### PR DESCRIPTION
**Pull request by scamille**
Edit: I need to test this first :-)

### CODE REVIEW

**Comment by mycroes** [comment]
LGTM

**Comment by mycroes** [comment]
By the way, I think both for Sally7 and S7NetPlus the way forward is to provide actual documentation, not a minor sample in readme only. I was thinking about ReadTheDocs, haven't made up my mind yet.

**Comment by scamille** [comment]
Ok after having my implementation working now I am sure that the example works like this :-)

**Comment by mycroes** [comment]
Hi @scamille, I changed the default branch to *main* and deleted the *develop* branch. Would you mind to recreate the PR against main?

**Pull request closed without merging**
